### ISSUE TITLE
swap image on click event

### ISSUE THREAD

**Issue by vivkay** [vivkay/pointer#1]
Hi @thomasjbradley !

Hope your summer is rockin'! 

Am working on a summer passion project to keep my coding fingers warmed up. But I've hit a js bump...

I want the logo icon at the top left to do two things:
1. swap colours on a click event (I have the same image saved in colour ready to swap)
2. toggle open a basic nav 

I tried using the code from our last project, but I can't seem to get the button to work! Could you take a look and tell me what I've broken?

THANKS SO MUCH!!

V

**Comment by vivkay** [comment]
...also is there any way to do this without the image being a background image? I don't remember why I styled my hamburger nav for our last term project that way. I ask because I'd prefer to have more control over the size of the icon (right now it has to be sized right in illustrator to display properly). Is there a better way?

:D

**Comment by vivkay** [comment]
...would I use an add and remove class to change the colour of the image? I thought about this, but then my brain started hurting. :pineapple:

**Comment by thomasjbradley** [comment]
Definitely just add/remove class to change the colour. By keeping it as a background image then you can swap the background image out, or try using a background sprite:
http://learn-the-web.algonquindesign.ca/topics/using-images/#sprites

So the Javascript click event would add/remove the class on the navigation & add/remove the class on the button.

**Comment by vivkay** [comment]
Used a toggle instead and it seems to work...but there's another issue (see new issue request coming in 3....2....)
