### ISSUE TITLE
nav logo alignment

### ISSUE THREAD

**Issue by vivkay** [vivkay/pointer#3]
@thomasjbradley I'm stumped on how to get my logo to align with my nav. This is what it looks like now at small and large screen sizes: 

![screen shot 2015-05-31 at 12 23 46 pm](https://cloud.githubusercontent.com/assets/6340292/7902704/0ec3159a-0790-11e5-9f6a-b596341ebbbf.png)

![screen shot 2015-05-31 at 12 23 53 pm](https://cloud.githubusercontent.com/assets/6340292/7902705/0ff885d0-0790-11e5-854f-ef18adeb6062.png)

I'd like the dog/logo to be above the small pointy triangle at all times. But I'm not sure how to make it stick because it's a background image... I tried giving it a left value but that didn't seem to do anything. This is what it's code looks like in css:

```
.logo-btn-off {
    height: 100px;
    width: 20%;
    left: 10px;
    overflow: hidden;
    text-indent: 100%;
    white-space: nowrap;
    background: transparent url("../img/logo-off.svg") no-repeat center center;
    padding: 0;
    margin: 20px;
    border: 0;
    z-index: 100;
}
```

I tried making the left value in percentage but that didn't work either.  

The panel wrapper has a left value of 35px and the small triangle on it has a value of 40px (so I'm guessing that I want the dog to be at left (35px + (40px/2)) = 55px ...? 

```
.panel-wrapper {
    position: relative;
    width: 50%;
    padding 30px;
    left: 35px;
    margin: 0;
    border: 5px solid #C4D6E8;
    color: #4F4242;
    background: white;
    -webkit-border-radius:10px;
    -moz-border-radius: 10px;
    border-radius: 10px;
}



/*styles outer border of small triangle*/
.panel-wrapper:before {
    content:"";
    position: absolute;
    top: -20px;
    bottom: auto;
    right: auto;
    left: 40px;
    border-width: 0 20px 20px;
    border-style: solid;
    border-color: #C4D6E8 transparent;
    display: block;
    width: 0;
}

/* styles inner fill of small triangle */
.panel-wrapper:after {
    content:"";
    position: absolute;
    top:-13px;
    bottom: auto;
    right: auto;
    left: 47px;
    border-width: 0px 13px 14px;
    border-style: solid;
    border-color: #EDF4F9 transparent;
    display: block;
    width: 0;
}
```

**Comment by thomasjbradley** [comment]
My quick guess would be to not set the width of the dog button in percents, but instead in a fix width.

**Comment by vivkay** [comment]
you rock! It works - except setting a 'left' value doesn't work which makes me curious...any ideas why that would be? It's not a problem yet but I'd like to know for future...

**Comment by thomasjbradley** [comment]
Is the button `position: relative` or `absolute`? If not the `left`, etc. properties won’t work.
